### PR TITLE
Fixed blocking Powershell CloudShell guide

### PR DESCRIPTION
**Pull request by perSCHOU**
I've updated the Powershell scripts used in the Cloudshell sessions to reference the new Az powershell modules instead, along with both updated parameters (skipped use "Searchstring") and method for getting Object ID for Group objects.

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
@mwasham 
Hi Michael,
Please review this pull request and advise.
Thanks, Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Thank you for your pull request.  I'm labeling this as an enhancement to be incorporated during the next update.

**Comment by ciphertxt** [comment]
@DawnmarieDesJardins This request doesn't need to be merged. The changes have been incorporated into the may-2019-update. @perSCHOU thanks so much for your contribution!

**Comment by DawnmarieDesJardins** [comment]
Closing this pull request as it's been incorporated into the May 2019 update currently in SME review.  Thanks!

**Pull request closed without merging**
